TYPO3:
  FormBuilder:
    newFormTemplates:
      'resource://TYPO3.FormBuilder/Private/NewFormTemplates/Blank.yaml': Blank
    defaultFormPersistenceIdentifier: 'resource://TYPO3.FormBuilder/Private/Forms/{identifier}.yaml'

    javaScripts:
      jQuery:
        sorting: 10
        files: ['resource://TYPO3.FormBuilder/Public/Library/jquery-1.7.1.min.js', 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js']
      ember:
        sorting: 15
        files: ['resource://TYPO3.FormBuilder/Public/Library/ember-0.9.4.js']
      dynatree:
        sorting: 20
        files: ['resource://TYPO3.FormBuilder/Public/Library/dynatree-1.2.0/src/jquery.dynatree.js']
      slickGrid:
        sorting: 25
        files:
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/lib/jquery.event.drag-2.0.min.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/slick.core.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/plugins/slick.cellrangedecorator.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/plugins/slick.cellrangeselector.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/plugins/slick.cellselectionmodel.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/plugins/slick.rowselectionmodel.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/plugins/slick.rowmovemanager.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/slick.editors.js'
          - 'resource://TYPO3.FormBuilder/Public/Library/SlickGrid/slick.grid.js'
      contextMenu:
        sorting: 30
        files: ['resource://TYPO3.FormBuilder/Public/Library/jQuery-contextMenu/jquery.contextMenu.js']
      application:
        files: ['resource://TYPO3.FormBuilder/Public/JavaScript/app.js']
        sorting: 100

    stylesheets:
      jQuery:
        sorting: 10
        files: ['http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css']
      dynatree:
        sorting: 20
        files: ['resource://TYPO3.FormBuilder/Public/Library/dynatree-1.2.0/src/skin/ui.dynatree.wrapped.css']
      slickGrid:
        sorting: 25
        files: ['resource://TYPO3.FormBuilder/Public/Library/SlickGrid/slick.grid.wrapped.css']
      contextMenu:
        sorting: 30
        files: ['resource://TYPO3.FormBuilder/Public/Library/jQuery-contextMenu/jquery.contextMenu.wrapped.css']
      application:
        sorting: 100
        files: ['resource://TYPO3.FormBuilder/Public/style.css']

    handlebarsTemplates:
      AvailableFormElements: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/AvailableFormElements.html
      FormTree: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/FormTree.html
      IdentifierEditor: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/IdentifierEditor.html
      PropertyGridEditor: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/PropertyGridEditor.html
      PropertyPanelTitle: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/PropertyPanelTitle.html
      RequiredValidatorEditor: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/RequiredValidatorEditor.html
      TextEditor: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/TextEditor.html
      FinisherTitle: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/FinisherTitle.html
      Finisher-Email: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/Finisher-Email.html
      Finisher-Redirect: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/Finisher-Redirect.html
      ValidatorEditor-Default: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/ValidatorEditor-Default.html
      ValidatorEditor-MinimumMaximum: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/ValidatorEditor-MinimumMaximum.html
      ValidatorEditor-SimpleValue: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/ValidatorEditor-SimpleValue.html
      ValidatorEditor: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/ValidatorEditor.html
      RemoveElementEditor: resource://TYPO3.FormBuilder/Private/Templates/FormBuilder/RemoveElementEditor.html

  Form:
    supertypeResolver:
      hiddenProperties:
        formBuilder: formBuilder
    presets:
      ########### DEFAULT ###########
      default:
        formElementGroups:
          input:
            sorting: 100
            label: 'Input Form Elements'
          select:
            sorting: 200
            label: 'Select Form Elements'
          custom:
            sorting: 300
            label: 'Custom Form Elements'
          container:
            sorting: 400
            label: 'Container Form Elements'

        formElementTypes:
          'TYPO3.Form:Base':
            formBuilder:
              editors:
                elementType:
                  sorting: 100
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextOutput'
                  templateName: 'PropertyPanelTitle'
                identifier:
                  sorting: 110
                  viewName: 'TYPO3.FormBuilder.View.Editor.IdentifierEditor'
                label:
                  label: 'Label'
                  propertyPath: 'label'
                  sorting: 120
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextEditor'
          'TYPO3.Form:FormElement':
            formBuilder:
              editors:
                requiredValidator:
                  sorting: 800
                  viewName: 'TYPO3.FormBuilder.View.Editor.RequiredValidatorEditor'

                validation:
                  sorting: 900
                  viewName: 'TYPO3.FormBuilder.View.Editor.ValidatorEditor'

          'TYPO3.Form:Form':
            formBuilder:
              label: 'Form'
              _isCompositeRenderable: false
              _isTopLevel: true
              editors:
                submitButtonLabel:
                  sorting: 200
                  label: 'Submit Button Label'
                  propertyPath: 'renderingOptions.submitButtonLabel'
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextEditor'

                finisherHeadline:
                  sorting: 400
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextOutput'
                  templateName: 'FinisherTitle'
                  tagName: h2
                finishers:
                  sorting: 410
                  viewName: 'TYPO3.FormBuilder.View.Editor.FinisherEditor'
                  availableFinishers:
                    email:
                      label: 'Send Email'
                      name: 'TYPO3\Form\Finishers\EmailFinisher'
                      viewName: 'TYPO3.FormBuilder.View.Editor.FinisherEditor.EmailFinisherEditor'
                      availableFormats:
                        0: {key: 'plaintext', value: 'Plain Text'}
                        1: {key: 'html', value: 'HTML'}
                    redirect:
                      label: 'Redirect to controller/action'
                      name: 'TYPO3\Form\Finishers\RedirectFinisher'
                      templateName: 'Finisher-Redirect'


          'TYPO3.Form:RemovableMixin':
            formBuilder:
              editors:
                removeButton:
                  sorting: 999
                  viewName: 'TYPO3.FormBuilder.View.Editor.RemoveElementEditor'

          # group INPUT
          'TYPO3.Form:SingleLineText':
            formBuilder:
              label: 'Single-Line Text'
              group: input
              sorting: 100

          'TYPO3.Form:MultiLineText':
            formBuilder:
              label: 'Multi-Line Text'
              group: input
              sorting: 110

          # group SELECT
          'TYPO3.Form:Checkbox':
            formBuilder:
              label: 'Single Checkbox'
              group: select
              sorting: 100

          'TYPO3.Form:SingleSelectDropdown':
            formBuilder:
              label: 'Single Select (Dropdown)'
              group: select
              sorting: 110

          'TYPO3.Form:SingleSelectRadiobuttons':
            formBuilder:
              label: 'Single Select (Radiobuttons)'
              group: select
              sorting: 120

          'TYPO3.Form:MultipleSelectDropdown':
            formBuilder:
              label: 'Multiple Select (Dropdown)'
              group: select
              sorting: 130

          'TYPO3.Form:MultipleSelectCheckboxes':
            formBuilder:
              label: 'Multiple Select (Checkboxes)'
              group: select
              sorting: 140

          # group CUSTOM
          'TYPO3.Form:DatePicker':
            formBuilder:
              label: 'Date Picker'
              group: custom
              sorting: 100
              editors:
                validation:
                  availableValidators:
                    dateTimeRange:
                      label: 'Date/Time Range'
                      name: 'TYPO3\FLOW3\Validation\Validator\DateTimeRangeValidator'
                      viewName: 'TYPO3.FormBuilder.View.Editor.ValidatorEditor.MinimumMaximumValidatorEditor'
                      pathToMinimumOption: 'currentCollectionElement.options.earliestDate'
                      pathToMaximumOption: 'currentCollectionElement.options.latestDate'

          'TYPO3.Form:ImageUpload':
            formBuilder:
              label: 'Image Upload'
              group: custom
              sorting: 110

          # group CONTAINER
          'TYPO3.Form:Section':
            formBuilder:
              label: 'Section (Fieldset)'
              group: container
              sorting: 100
              _isCompositeRenderable: true

          'TYPO3.Form:Page':
            formBuilder:
              label: 'Page'
              group: container
              sorting: 110
              _isTopLevel: true
              _isCompositeRenderable: true

          'TYPO3.Form:PreviewPage':
            formBuilder:
              label: 'Preview Page'
              group: container
              sorting: 120
              _isTopLevel: true
              _isCompositeRenderable: false


          'TYPO3.Form:TextMixin':
            formBuilder:
              editors:
                placeholder:
                  sorting: 150
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextEditor'
                  label: 'Placeholder'
                  propertyPath: 'properties.placeholder'
                defaultValue:
                  sorting: 160
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextEditor'
                  label: 'Default Value'
                  propertyPath: 'defaultValue'
                validation:
                   availableValidators:
                    alphanumeric:
                      label: 'Alphanumeric'
                      sorting: 100
                      name: 'TYPO3\FLOW3\Validation\Validator\AlphanumericValidator'
                    text:
                      label: 'Non-XML Text'
                      sorting: 110
                      name: 'TYPO3\FLOW3\Validation\Validator\TextValidator'
                    stringLength:
                      label: 'String Length'
                      sorting: 120
                      name: 'TYPO3\FLOW3\Validation\Validator\StringLengthValidator'
                      viewName: 'TYPO3.FormBuilder.View.Editor.ValidatorEditor.MinimumMaximumValidatorEditor'
                      required: false
                    emailAddress:
                      label: 'EMail'
                      sorting: 130
                      name: 'TYPO3\FLOW3\Validation\Validator\EmailAddressValidator'
                      required: false

                    integer:
                      label: 'Integer Number'
                      sorting: 200
                      name: 'TYPO3\FLOW3\Validation\Validator\IntegerValidator'
                    float:
                      label: 'Floating-point Number'
                      sorting: 210
                      name: 'TYPO3\FLOW3\Validation\Validator\FloatValidator'
                    numberRange:
                      label: 'Number Range'
                      sorting: 220
                      name: 'TYPO3\FLOW3\Validation\Validator\NumberRangeValidator'
                      viewName: 'TYPO3.FormBuilder.View.Editor.ValidatorEditor.MinimumMaximumValidatorEditor'

                    regularExpression:
                      label: 'Regular Expression'
                      fieldLabel: 'Regular Expression'
                      fieldExplanationText: 'Enter a valid PHP PCRE Regular Expression here.'
                      sorting: 300
                      name: 'TYPO3\FLOW3\Validation\Validator\RegularExpressionValidator'
                      viewName: 'TYPO3.FormBuilder.View.Editor.ValidatorEditor.SimpleValueValidatorEditor'
                      pathToEditedValue: 'currentCollectionElement.options.regularExpression'

          'TYPO3.Form:SelectionMixin':
            formBuilder:
              editors:
                options:
                  sorting: 200
                  viewName: 'TYPO3.FormBuilder.View.Editor.PropertyGrid'
                  # TODO: rename to "optionListPath"?
                  propertyPath: 'properties.options'
                  isSortable: true
                  enableAddRow: true
                  enableContextMenu: true
                  columns:
                    0:
                      field: '_value'
                      name: 'Label'
                      editor: 'TYPO3.FormBuilder.View.Editor.PropertyGrid.TextCellEditor'
                    1:
                      field: '_key'
                      name: 'Value'
                      editor: 'TYPO3.FormBuilder.View.Editor.PropertyGrid.TextCellEditor'
          'TYPO3.Form:SingleSelectionMixin':
            formBuilder:
              editors:
                options:
                  shouldShowPreselectedValueColumn: 'single'
          'TYPO3.Form:MultiSelectionMixin':
            formBuilder:
              editors:
                options:
                  shouldShowPreselectedValueColumn: 'multiple'
                validation:
                  availableValidators:
                    count:
                      label: 'Number of submitted values'
                      sorting: 100
                      name: 'TYPO3\FLOW3\Validation\Validator\CountValidator'
                      viewName: 'TYPO3.FormBuilder.View.Editor.ValidatorEditor.MinimumMaximumValidatorEditor'
