TYPO3:
  Form:
    supertypeResolver:
      hiddenProperties:
        formBuilder: formBuilder
    Presets:
      ########### DEFAULT ###########
      Default:
        formElementGroups:
          simple:
            sorting: 100
            label: 'Simple Form Elements'
          composite:
            sorting: 200
            label: 'Composite Form Elements'
        cssFiles: ['/_Resources/Static/Packages/TYPO3.FormExample/Css/bootstrap.min.css', '/_Resources/Static/Packages/TYPO3.FormExample/Css/main.css']
        formElementTypes:
          'TYPO3.Form:Base':
            formBuilder:
              #todo rename to "editors"
              formFieldEditors:
                elementType:
                  sorting: 100
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextOutput'
                  templateName: 'PropertyPanelTitle'
                labelAndIdentifier:
                  sorting: 110
                  viewName: 'TYPO3.FormBuilder.View.Editor.LabelEditor'

          'TYPO3.Form:Page':
            formBuilder:
              label: 'Page'
              group: 'composite'
              sorting: 100
              # todo rename this to "isPage"
              _isCompositeRenderable: true

          'TYPO3.Form:FormElement':
            formBuilder:
              formFieldEditors:
                requiredValidator:
                  sorting: 800
                  viewName: 'TYPO3.FormBuilder.View.Editor.RequiredValidatorEditor'

                validation:
                  sorting: 900
                  viewName: 'TYPO3.FormBuilder.View.Editor.ValidatorEditor'

          'TYPO3.Form:Section':
            formBuilder:
              label: 'Section (Fieldset)'
              group: 'composite'
              sorting: 200

          'TYPO3.Form:Textfield':
            formBuilder:
              label: 'Simple Textfield'
              group: simple
              sorting: 100

          'TYPO3.Form:Textarea':
            formBuilder:
              label: 'Multiline Text'
              group: simple
              sorting: 110

          'TYPO3.Form:Checkbox':
            formBuilder:
              label: 'Single Checkbox'
              group: simple
              sorting: 120

          'TYPO3.Form:Checkboxes':
            formBuilder:
              label: 'Checkbox List'
              group: simple
              sorting: 130

          'TYPO3.Form:Radiobuttons':
            formBuilder:
              label: 'Radio Button List'
              group: simple
              sorting: 140

          'TYPO3.Form:Select':
            formBuilder:
              label: 'Select Field'
              group: simple
              sorting: 150

          'TYPO3.Form:Date':
            formBuilder:
              label: 'Date Selection'
              group: simple
              sorting: 160

          'TYPO3.Form:ImageUpload':
            formBuilder:
              label: 'Image Upload'
              group: simple
              sorting: 170

          'TYPO3.Form:TextMixin':
            formBuilder:
              formFieldEditors:
                placeholder:
                  sorting: 150
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextEditor'
                  label: 'Placeholder'
                  propertyPath: 'properties.placeholder'
                defaultValue:
                  sorting: 160
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextEditor'
                  label: 'Default Value'
                  propertyPath: 'defaultValue'
                validation:
                   availableValidators:
                    email:
                      label: 'EMail'
                      name: 'TYPO3\FLOW3\Validation\Validator\EmailAddressValidator'
                      required: false
                    stringLength:
                      label: 'String Length'
                      name: 'TYPO3\FLOW3\Validation\Validator\StringLengthValidator'
                      viewName: 'TYPO3.FormBuilder.View.Editor.ValidatorEditor.MinimumMaximumValidatorEditor'
                      required: true

          'TYPO3.Form:SelectionMixin':
            formBuilder:
              formFieldEditors:
                options:
                  sorting: 200
                  viewName: 'TYPO3.FormBuilder.View.Editor.PropertyGrid'
                  # TODO: rename to "optionListPath"?
                  propertyPath: 'properties.options'
                  isSortable: true
                  enableAddRow: true
                  columns:
                    0:
                      field: '_key'
                      name: 'Value'
                      editor: 'TextCellEditor'
                    1:
                      field: '_value'
                      name: 'Label'
                      editor: 'TextCellEditor'
