TYPO3:
  Form:
    supertypeResolver:
      hiddenProperties:
        formBuilder: formBuilder
    Presets:
      ########### DEFAULT ###########
      Default:
        formElementGroups:
          input:
            sorting: 100
            label: 'Input Form Elements'
          select:
            sorting: 200
            label: 'Select Form Elements'
          custom:
            sorting: 300
            label: 'Custom Form Elements'
          container:
            sorting: 400
            label: 'Container Form Elements'

        cssFiles: ['/_Resources/Static/Packages/TYPO3.FormExample/Css/bootstrap.min.css', '/_Resources/Static/Packages/TYPO3.FormExample/Css/main.css']
        formElementTypes:
          'TYPO3.Form:Base':
            formBuilder:
              #todo rename to "editors"
              formFieldEditors:
                elementType:
                  sorting: 100
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextOutput'
                  templateName: 'PropertyPanelTitle'
                labelAndIdentifier:
                  sorting: 110
                  viewName: 'TYPO3.FormBuilder.View.Editor.LabelEditor'
          'TYPO3.Form:FormElement':
            formBuilder:
              formFieldEditors:
                requiredValidator:
                  sorting: 800
                  viewName: 'TYPO3.FormBuilder.View.Editor.RequiredValidatorEditor'

                validation:
                  sorting: 900
                  viewName: 'TYPO3.FormBuilder.View.Editor.ValidatorEditor'
          'TYPO3.Form:Form':
            formBuilder:
              label: 'Form'

          # group INPUT
          'TYPO3.Form:SingleLineText':
            formBuilder:
              label: 'Single-Line Text'
              group: input
              sorting: 100

          'TYPO3.Form:MultiLineText':
            formBuilder:
              label: 'Multi-Line Text'
              group: input
              sorting: 110

          # group SELECT
          'TYPO3.Form:Checkbox':
            formBuilder:
              label: 'Single Checkbox'
              group: select
              sorting: 100

          'TYPO3.Form:SingleSelectDropdown':
            formBuilder:
              label: 'Single Select (Dropdown)'
              group: select
              sorting: 110

          'TYPO3.Form:SingleSelectRadiobuttons':
            formBuilder:
              label: 'Single Select (Radiobuttons)'
              group: select
              sorting: 120

          'TYPO3.Form:MultipleSelectDropdown':
            formBuilder:
              label: 'Multiple Select (Dropdown)'
              group: select
              sorting: 130

          'TYPO3.Form:MultipleSelectCheckboxes':
            formBuilder:
              label: 'Multiple Select (Checkboxes)'
              group: select
              sorting: 140

          # group CUSTOM
          'TYPO3.Form:DatePicker':
            formBuilder:
              label: 'Date Picker'
              group: custom
              sorting: 100

          'TYPO3.Form:ImageUpload':
            formBuilder:
              label: 'Image Upload'
              group: custom
              sorting: 110

          # group CONTAINER
          'TYPO3.Form:Page':
            formBuilder:
              label: 'Page'
              group: container
              sorting: 100
              _isPage: true

          'TYPO3.Form:Section':
            formBuilder:
              label: 'Section (Fieldset)'
              group: container
              sorting: 200
              _isCompositeRenderable: true


          'TYPO3.Form:TextMixin':
            formBuilder:
              formFieldEditors:
                placeholder:
                  sorting: 150
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextEditor'
                  label: 'Placeholder'
                  propertyPath: 'properties.placeholder'
                defaultValue:
                  sorting: 160
                  viewName: 'TYPO3.FormBuilder.View.Editor.TextEditor'
                  label: 'Default Value'
                  propertyPath: 'defaultValue'
                validation:
                   availableValidators:
                    email:
                      label: 'EMail'
                      name: 'TYPO3\FLOW3\Validation\Validator\EmailAddressValidator'
                      required: false
                    stringLength:
                      label: 'String Length'
                      name: 'TYPO3\FLOW3\Validation\Validator\StringLengthValidator'
                      viewName: 'TYPO3.FormBuilder.View.Editor.ValidatorEditor.MinimumMaximumValidatorEditor'
                      required: true

          'TYPO3.Form:SelectionMixin':
            formBuilder:
              formFieldEditors:
                options:
                  sorting: 200
                  viewName: 'TYPO3.FormBuilder.View.Editor.PropertyGrid'
                  # TODO: rename to "optionListPath"?
                  propertyPath: 'properties.options'
                  isSortable: true
                  enableAddRow: true
                  columns:
                    0:
                      field: '_key'
                      name: 'Value'
                      editor: 'TextCellEditor'
                    1:
                      field: '_value'
                      name: 'Label'
                      editor: 'TextCellEditor'
